### PR TITLE
latest_year works for yyyy-y patterns; fix two other errors

### LINKED ISSUE #33: parse 'yyyy-y' pattern
DLME Cambridge collections have some of these:

```
genizah/genizah-997.xml:98:                     <origDate calendar="Gregorian" notBefore="" notAfter="">1040–1 CE</origDate>

```

### PR DESCRIPTION
**Pull request by ndushay**
## Why was this change made?

Closes #33

DLME colls Cambridge, Bodleian/Armenian and Harvard IHP all have date strings like '1040–1 CE'

This will allow for more complete date ranges for records with such date strings.

## Was the documentation (README, API, wiki, ...) updated?

yes, README

### CODE REVIEW

File: lib/parse_date.rb [hunk 1]
```diff
@@ -72,7 +72,7 @@ def self.range_array(first_year, last_year)
     return [] unless last_year || first_year
     return [first_year] if last_year.nil? && first_year
     return [last_year] if first_year.nil? && last_year
-    raise(StandardError, "unable to create year range array from #{first_year}, #{last_year}") unless
+    raise(ParseDate::Error, "unable to create year range array from #{first_year}, #{last_year}") unless
```
Comment (ndushay) [inline lib/parse_date.rb]: we want this gem to throw errors specific to this gem - this is the one occurrence where that was not the case.

File: lib/parse_date/int_from_string.rb [hunk 2]
```diff
@@ -75,7 +76,7 @@ def self.latest_year(date_str)
       unless result
         # try removing brackets between digits in case we have 169[5] or [18]91
         no_brackets = ParseDate.send(:remove_brackets, date_str)
-        return earliest_year(no_brackets) if no_brackets
+        return latest_year(no_brackets) if no_brackets
```
Comment (ndushay) [inline lib/parse_date/int_from_string.rb]: whoops!  super duper bad error in the `latest_year` method.
